const os = require('os')

// console.log(os)
// console.log(os.version())
// console.log(os.cpus())
// console.log(os.cpus()[0])
// console.log(os.cpus()[0].speed)
// console.log(os.freemem())
// console.log(os.machine())
console.log(os.totalmem())